# Generated by Django 5.0.3 on 2024-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_patologias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patologia', models.TextField(max_length=255)),
                ('sintomas', models.TextField(max_length=255)),
                ('observacoes', models.TextField(max_length=255)),
            ],
        ),
    ]
